### ISSUE TITLE
[Error] Problem during Pull container images 

### ISSUE THREAD

**Issue by ariscahyadi** [ChameleonCloud/chi-in-a-box#77]
Hello,

I tried to run this software, but I have a problem during pulling the docker images.
It seems it is required API authentication to the Chameleon Docker repository.

`line 31, in create_api_error_from_http_exception\\n    raise cls(e, response=response, explanation=explanation)\\nAPIError: 500 Server Error: Internal Server Error (\"Get https://docker.chameleoncloud.org/v2/: no basic auth credentials\")\\n'"}
`
Thank you,
Aris.

**Comment by diurnalist** [comment]
HI @ariscahyadi -- the Docker registry requires authentication. You can login like this:

```shell
docker login docker.chameleoncloud.org
```

Enter your Chameleon username and password to authenticate. After that it should work fine.

**Comment by ariscahyadi** [comment]
> HI @ariscahyadi -- the Docker registry requires authentication. You can login like this:
> 
> ```shell
> docker login docker.chameleoncloud.org
> ```
> 
> Enter your Chameleon username and password to authenticate. After that it should work fine.

Thanks @diurnalist -- But, it seems I am not authorized to access it.

```
[ncl@openstack-dev chi-in-a-box]$ sudo docker login docker.chameleoncloud.org
Username: ariscr
Password: 
Error response from daemon: login attempt to http://docker.chameleoncloud.org/v2/ failed with status: 401 Unauthorized
```

**Comment by diurnalist** [comment]
@ariscahyadi I think the issue is that you are not yet part of a project w/ an active allocation on Chameleon. I have sent you mail on a different channel with some steps on how you can proceed.

**Comment by samiemostafavi** [comment]
Hi,

I am facing similar issue when running:
https://chameleoncloud.gitbook.io/chi-in-a-box/setup-guides/evaluation-site/bring-up-the-control-plane#downloading-containers

By running

`./cc-ansible --site /opt/site-config pull`

Ansible crashes:

`500 Server Error for http+docker://localhost/v1.41/auth: Internal Server Error (\"login attempt to https://docker.chameleoncloud.org/v2/ failed with status: 404 Not Found`

Am I missing a credential? Because it is not mentioned anywhere in this [document](https://chameleoncloud.gitbook.io/chi-in-a-box/setup-guides/evaluation-site/bring-up-the-control-plane).

Best,
Samie
